apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvk1
spec:
  capacity:
    storage: 1Gi
  storageClassName: myscn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"